#!/bin/bash

# Copyright 2022-2024 jhnc-oss
# Copyright 2019-2021 Max Goltzsche
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Note: Based on https://github.com/mgoltzsche/jenkins-jnlp-slave/blob/2eac7c0e1e70bfa4bc138ed9c9817da245e9309c/docker

# This script delegates docker commands to podman while transforming
# a few in order to be compatible with docker/jenkins workflow plugin


exec_podman() {
    exec /usr/bin/podman "$@"
}


case "$1" in
    # Fake docker version
    '-v')
        echo 'Docker version 18.06.1-ce, build e68fc7a'
    ;;

    # Inject oom-score-adj from host in order to run within container with limited resources
    # Remove user mapping (since already mapped)
    run)
        shift
        OOMSCORE=$(cat /proc/self/oom_score_adj)
        if [ "$1 $2 $3" = '-t -d -u' ]; then
            shift 4
            exec_podman run -t -d --oom-score-adj "$OOMSCORE" "$@"
        else
            exec_podman run --oom-score-adj "$OOMSCORE" "$@"
        fi
    ;;

    # Convert ps format option
    top)
        shift
        if [ "$2" = '-eo' ]; then
            CONTAINERID="$1"
            shift 2
            exec_podman top "$CONTAINERID" "${@}"
        else
            exec_podman top "$@"
        fi
    ;;

    # Remove https:// prefix
    login)
        shift
        REGISTRY="${*:$#}"
        LOGIN_ARGS=("${@:1:$#-1}")

        exec_podman login "${LOGIN_ARGS[@]}" "${REGISTRY##https://}"
    ;;

    *)
        exec_podman "$@"
    ;;
esac
